- name: Create Prometheus config directory
  file:
    path: /opt/prometheus
    state: directory

- name: Copy Prometheus config
  copy:
    src: files/prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Run Prometheus
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    ports:
      - "9091:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart_policy: always

- name: Run Grafana
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    ports:
      - "3005:3000"
    restart_policy: always

