- name: Stop and remove old frontend container
  docker_container:
    name: frontend
    state: absent
    force_kill: true

- name: Run frontend container
  docker_container:
    name: frontend
    image: portfolio-frontend_frontend:latest
    state: started
    ports:
      - "3000:80"
    restart_policy: always

