version: "3"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ahilsakti@1218
      MYSQL_DATABASE: portfolio_db
    ports:
      - "3307:3306"
    networks:
      - backend-net

  backend:
    build: .
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - backend-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ahilsakti@1218

networks:
  backend-net:

