version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ahilsakti@1218
      MYSQL_DATABASE: portfolio_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../portfolio-backend
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ahilsakti@1218
    depends_on:
      - mysql

  frontend:
    build:
      context: ../portfolio-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3005:3000"

volumes:
  mysql_data:

